sudo: false
language: java
addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8
env:
  - TEST_DIR=src/Server
script:
  - jdk_switcher use oraclejdk8
  - cd $TEST_DIR && ant server
